# Generated by Django 5.0.2 on 2024-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Tipo de Negocio',
                'verbose_name_plural': 'Tipo de Negocio',
            },
        ),
    ]
