# Generated by Django 5.0.2 on 2024-02-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousesvirtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_medida', models.CharField(max_length=4)),
                ('nombre_medida', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidad de Medida',
            },
        ),
    ]
