# Generated by Django 5.0.2 on 2024-02-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousesvirtual', '0003_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero_habitantes', models.PositiveBigIntegerField()),
                ('extension', models.PositiveBigIntegerField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousesvirtual.pais')),
                ('unidad_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousesvirtual.unidad_medida')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudad',
            },
        ),
    ]
