# Generated by Django 5.0.2 on 2024-02-20 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousesvirtual', '0004_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=40)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousesvirtual.ciudad')),
            ],
        ),
    ]
