# Generated by Django 5.0.2 on 2024-02-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousesvirtual', '0005_zonas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonas',
            options={'verbose_name': 'Zona', 'verbose_name_plural': 'Zona'},
        ),
    ]
