# Generated by Django 5.0.2 on 2024-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousesvirtual', '0006_alter_zonas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonas',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
    ]
