# Generated by Django 5.0.2 on 2024-04-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousesvirtual', '0007_zonas_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_nac', models.DateField()),
                ('ciudad', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
