# Generated by Django 5.0.2 on 2024-03-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicaciones',
            old_name='nombre',
            new_name='cliente',
        ),
    ]
