# Generated by Django 5.0.2 on 2024-03-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_rename_nombre_publicaciones_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='contador',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
