# Generated by Django 5.0.2 on 2024-04-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_publicaciones_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='contador',
            field=models.IntegerField(default=0),
        ),
    ]
