# Generated by Django 5.0.2 on 2024-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDocIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo Doc Identidad',
                'verbose_name_plural': 'Tipos Doc Identidad',
            },
        ),
    ]
