# Generated by Django 5.0.2 on 2024-02-12 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
        ('warehousesvirtual', '0004_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('doc_identidad', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
                ('comentarios', models.TextField(blank=True)),
                ('logo_raw', models.FileField(upload_to='static/imagenes')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousesvirtual.ciudad')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousesvirtual.pais')),
                ('tipo_identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.tiposdocidentidad')),
                ('tipo_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousesvirtual.tipo_negocio')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
