# Generated by Django 5.0.2 on 2024-03-04 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_clientes_zona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userclient',
            unique_together={('nombre_cliente', 'nombre_user')},
        ),
    ]
